//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HoaDon
    {
        public int maHD { get; set; }
        public string maSP { get; set; }
        public int maKichCo { get; set; }
        public Nullable<double> giaBan { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> thanhTien { get; set; }
        public string maSPDoi { get; set; }
        public Nullable<System.DateTime> ngayDoi { get; set; }
        public Nullable<bool> tinhTrangDoi { get; set; }
    
        public virtual hoaDon hoaDon { get; set; }
        public virtual kichCo kichCo { get; set; }
        public virtual sanPham sanPham { get; set; }
    }
}
