//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoaDon()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
    
        public int maHD { get; set; }
        public string maNV { get; set; }
        public Nullable<int> maKH { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<int> maKM { get; set; }
        public Nullable<double> tienGiam { get; set; }
        public Nullable<double> tienKhachDua { get; set; }
        public Nullable<double> tienThua { get; set; }
        public Nullable<bool> tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual khachHang khachHang { get; set; }
        public virtual khuyenMai khuyenMai { get; set; }
        public virtual nhanVien nhanVien { get; set; }
    }
}
