//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class khuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khuyenMai()
        {
            this.hoaDons = new HashSet<hoaDon>();
        }
    
        public int maKM { get; set; }
        public string tenKM { get; set; }
        public Nullable<int> giaTriGiam { get; set; }
        public Nullable<System.DateTime> ngayBD { get; set; }
        public Nullable<System.DateTime> ngayKT { get; set; }
        public Nullable<bool> tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoaDon> hoaDons { get; set; }
    }
}
