//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class kichCo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kichCo()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
            this.CT_PhieuNhap = new HashSet<CT_PhieuNhap>();
            this.sanPham_KichCo = new HashSet<sanPham_KichCo>();
        }
    
        public int maKichCo { get; set; }
        public Nullable<int> kichCo1 { get; set; }
        public Nullable<bool> tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanPham_KichCo> sanPham_KichCo { get; set; }
    }
}
