//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBGEntities : DbContext
    {
        public QLBGEntities()
            : base("name=QLBGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual DbSet<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual DbSet<hoaDon> hoaDons { get; set; }
        public virtual DbSet<khachHang> khachHangs { get; set; }
        public virtual DbSet<khuyenMai> khuyenMais { get; set; }
        public virtual DbSet<kichCo> kichCoes { get; set; }
        public virtual DbSet<loaiSP> loaiSPs { get; set; }
        public virtual DbSet<ncc> nccs { get; set; }
        public virtual DbSet<nhanVien> nhanViens { get; set; }
        public virtual DbSet<phanQuyen> phanQuyens { get; set; }
        public virtual DbSet<phieuNhap> phieuNhaps { get; set; }
        public virtual DbSet<sanPham> sanPhams { get; set; }
        public virtual DbSet<sanPham_KichCo> sanPham_KichCo { get; set; }
    }
}
