//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanQuyen
    {
        public int maQuyen { get; set; }
        public string tenQuyen { get; set; }
        public Nullable<bool> qLyTK { get; set; }
        public Nullable<bool> qLyBH { get; set; }
        public Nullable<bool> qLySP { get; set; }
        public Nullable<bool> qLyNV { get; set; }
        public Nullable<bool> qLyKH { get; set; }
        public Nullable<bool> qLyKM { get; set; }
        public Nullable<bool> qLyNH { get; set; }
        public Nullable<bool> xemThongKe { get; set; }
    }
}
