//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieuNhap()
        {
            this.CT_PhieuNhap = new HashSet<CT_PhieuNhap>();
        }
    
        public int maPN { get; set; }
        public string maNV { get; set; }
        public Nullable<int> maNCC { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<bool> tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual ncc ncc { get; set; }
        public virtual nhanVien nhanVien { get; set; }
    }
}
